### ISSUE TITLE
web server no workie

### ISSUE THREAD

**Issue by deepgray** [BinaryAnalysisPlatform/qira#194]
usign the most recent Kali 2016 load, installed qira with no errors.

starting it up appears that the webserver crashes...nmap only shows port 4000 and 3002 is non connectable vi nc to verify.

root@kali2-amd64:~/Desktop# qira -s /bin/ls
/root/Desktop/qira/middleware/qira_webserver.py:41: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO, emit
*** program is /bin/ls with hash 85c05d8c0e085040e5eda54de4638d4485b1d22d
**** using /root/Desktop/qira/tracers/qemu/qemu-2.5.1/x86_64-linux-user/qemu-x86_64 for 0x3e
no qira server found, starting it
*** deleting old runs
**** listening on <socket fileno=7 sock=0.0.0.0:4000>
****** starting WEB SERVER on 0.0.0.0:3002
Traceback (most recent call last):
  File "/root/Desktop/qira/middleware/qira.py", line 104, in <module>
    qira_webserver.run_server(args, program)
  File "/root/Desktop/qira/middleware/qira_webserver.py", line 434, in run_server
    socketio.run(app, host=qira_config.HOST, port=qira_config.WEB_PORT, log=open("/dev/null", "w"))
  File "/root/Desktop/qira/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 529, in run
    log=log, **kwargs)
TypeError: type object got multiple values for keyword argument 'log'
root@kali2-amd64:~/Desktop#

**Comment by hrdn** [comment]
i got same problem too

**Comment by DuckLL** [comment]
You should try #192  solution.
