### ISSUE TITLE
analyzer crash

### ISSUE THREAD

**Issue by geohot** [BinaryAnalysisPlatform/qira#96]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ghotz/qira/middleware/qira_program.py", line 390, in analysis_thread
    qira_analysis.analyse_calls(self.program, self.flow)
  File "/home/ghotz/qira/middleware/qira_analysis.py", line 338, in analyse_calls
    endclnum = get_last_instr(trace.dmap,clnum)
  File "/home/ghotz/qira/middleware/qira_analysis.py", line 291, in get_last_instr
    myd = dmap[clnum]+1
IndexError: list index out of range

**Comment by nedwill** [comment]
Did this happen in a particular context or with a specific test case? I was going to look at cleaning up some of the analyzer code against the new static API and if there's an actual crash happening that should be first priority.

**Comment by nedwill** [comment]
Oh, it seems like it happens when you have >1 traces open.
